// Local Bangs – resolves !bangs inside Firefox.
//
// The default search engine is https://unduck.link?q=%s. This intercepts that
// request before it leaves the browser and redirects straight to the target,
// so nothing is fetched from unduck. If the extension is disabled, real unduck
// still works as a fallback.
//
// BANGS (bangs.js, generated by build.sh) maps trigger → [url template, domain].

// Personal bangs / overrides: trigger → url template ({{{s}}} = search terms).
const CUSTOM = {
  // "ghr": "https://github.com/{{{s}}}",
};

const DEFAULT_BANG = "g";
const BANG_RE = /!(\S+)/i;

for (const [t, u] of Object.entries(CUSTOM)) {
  BANGS[t.toLowerCase()] = [u, new URL(u.replace("{{{s}}}", "")).hostname];
}
const fallback = BANGS[DEFAULT_BANG];

function resolve(query) {
  const match = query.match(BANG_RE);
  const [template, domain] = (match && BANGS[match[1].toLowerCase()]) || fallback;
  // drop the first bang (and the whitespace after it)
  const clean = query.replace(/!\S+\s*/i, "").trim();

  // bang on its own ("!yt") → the site's homepage
  if (!clean && domain) return `https://${domain}`;

  // same as unduck: keep slashes readable (e.g. "!gh owner/repo")
  return template.replace(
    "{{{s}}}",
    encodeURIComponent(clean).replace(/%2F/g, "/"),
  );
}

browser.webRequest.onBeforeRequest.addListener(
  ({ url }) => {
    const q = new URL(url).searchParams.get("q");
    if (!q || !q.trim()) return {}; // plain unduck.link visit – let it load
    return { redirectUrl: resolve(q) };
  },
  { urls: ["https://unduck.link/*"], types: ["main_frame"] },
  ["blocking"],
);
