#!/bin/sh
# Refresh DuckDuckGo's bang list, regenerate bangs.js and package the extension.
set -e
cd "$(dirname "$0")"

curl -fsSL --compressed -o bangs-ddg.json https://duckduckgo.com/bang.js

python3 - <<'EOF'
import json
bangs = json.load(open("bangs-ddg.json"))
table = {b["t"].lower(): [b["u"], b["d"]] for b in bangs}
with open("bangs.js", "w") as f:
    f.write("// generated by build.sh from https://duckduckgo.com/bang.js – do not edit\n")
    f.write("const BANGS = ")
    json.dump(table, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")
print(f"{len(table)} bangs")
EOF

rm -f local-bangs.zip
zip -q -X local-bangs.zip manifest.json background.js bangs.js
echo "packaged local-bangs.zip"
