#!/bin/sh
# Refresh DuckDuckGo's bang list, regenerate bangs.js and package the extension.
#   ./build.sh            download the latest bang list, then package
#   ./build.sh --offline  package with the existing bangs-ddg.json
set -e
cd "$(dirname "$0")"

if [ "$1" != "--offline" ]; then
  curl -fsSL --compressed -o bangs-ddg.json https://duckduckgo.com/bang.js
fi

python3 - <<'PY'
import json
bangs = json.load(open("bangs-ddg.json"))
table = {b["t"].lower(): [b["u"], b["d"]] for b in bangs}
with open("bangs.js", "w") as f:
    f.write("// generated by build.sh from https://duckduckgo.com/bang.js – do not edit\n")
    f.write("const BANGS = ")
    json.dump(table, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")
print(f"{len(table)} bangs")
PY

rm -f local-bangs.zip
zip -q -X -r local-bangs.zip manifest.json bangs.js resolve.js background.js options icons LICENSE -x "*.DS_Store"
echo "packaged local-bangs.zip"
