// Bang resolution, shared by the background script and the options page.
//
// BANGS (bangs.js, generated by build.sh) maps trigger → [url template, domain].
// Templates use {{{s}}} for the URL-encoded search terms.

const DEFAULT_SETTINGS = {
  // where queries without a (known) bang go
  defaultUrl: "https://www.google.com/search?q={{{s}}}",
  // personal bangs / overrides: trigger → url template
  custom: {},
};

// a bang is "!" + trigger at the start of the query or after whitespace,
// so "wow!" or "a!b" are left alone
const BANG_RE = /(^|\s)!(\S+)/;

function hostOf(template) {
  try {
    return new URL(template.replace("{{{s}}}", "")).hostname;
  } catch {
    return "";
  }
}

function lookupBang(trigger, settings) {
  const t = trigger.toLowerCase();
  const custom = settings.custom?.[t];
  if (custom) return [custom, hostOf(custom)];
  return BANGS[t] ?? null;
}

function resolveBang(query, settings) {
  let template = settings.defaultUrl;
  let domain = hostOf(template);
  let clean = query;

  const match = query.match(BANG_RE);
  const bang = match && lookupBang(match[2], settings);
  if (bang) {
    [template, domain] = bang;
    // drop the bang (and the whitespace after it); unknown bangs stay in the query
    clean = query.slice(0, match.index) + match[1] + query.slice(match.index + match[0].length).trimStart();
  }
  clean = clean.trim();

  // bang on its own ("!yt") → the site's homepage
  if (!clean && bang && domain) return `https://${domain}`;

  // keep slashes readable (e.g. "!gh owner/repo"), same as unduck
  return template.replaceAll("{{{s}}}", encodeURIComponent(clean).replace(/%2F/g, "/"));
}
